---
- hosts: prod-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy Final_Project application
    command: sudo docker run -itd -p 8081:8081 rama48/final_project:1.0
